name: CI Pipeline for Fraud Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: transactions_db
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run backend tests
      run: |
        cd backend
        pytest --disable-warnings

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Build backend Docker image
      run: |
        docker build -t fraud-detection-backend:latest ./backend

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build backend Docker image
      run: |
        docker build -t fraud-detection-backend:latest ./backend
        docker tag fraud-detection-backend:latest samuelokasia/realtime-fraud-backend:latest
        docker push samuelokasia/realtime-fraud-backend:latest

    - name: Build frontend Docker image
      run: |
        docker build -t fraud-detection-frontend:latest ./frontend
        docker tag fraud-detection-frontend:latest samuelokasia/realtime-fraud-frontend:latest
        docker push samuelokasia/realtime-fraud-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    # Register a new ECS backend task definition
    - name: Register new ECS backend task definition
      run: |
        aws ecs register-task-definition \
          --family fraud-backend-task \
          --cli-input-json file://ecs-backend-task-definition.json

    # Register a new ECS frontend task definition
    - name: Register new ECS frontend task definition
      run: |
        aws ecs register-task-definition \
          --family fraud-frontend-task \
          --cli-input-json file://ecs-frontend-task-definition.json

    # Update ECS services to use the new task definition revision
    - name: Deploy Backend to ECS
      run: |
        aws ecs update-service --cluster fraud-detection-cluster \
          --service fraud-backend-service \
          --force-new-deployment

    - name: Deploy Frontend to ECS
      run: |
        aws ecs update-service --cluster fraud-detection-cluster \
          --service fraud-frontend-service \
          --force-new-deployment